# Generated by Django 3.2.9 on 2021-11-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211104_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
